# Generated by Django 4.2.5 on 2023-10-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pt_main',
            name='patents_pt__search__a861b6_gin',
        ),
        migrations.RemoveField(
            model_name='pt_main',
            name='search_vector',
        ),
    ]
