# Generated by Django 4.2.5 on 2023-09-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_claim',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim', to='patents.pt_main'),
        ),
    ]
