# Generated by Django 4.2.5 on 2023-09-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pt_abstract',
            name='patents_pt__search__7b4f93_gin',
        ),
        migrations.RemoveIndex(
            model_name='pt_claim',
            name='patents_pt__search__612671_gin',
        ),
        migrations.RemoveIndex(
            model_name='pt_disclosure',
            name='patents_pt__search__bb6434_gin',
        ),
        migrations.RemoveIndex(
            model_name='pt_interested_party',
            name='patents_pt__search__30ee24_gin',
        ),
        migrations.RemoveIndex(
            model_name='pt_ipc_classification',
            name='patents_pt__search__785a99_gin',
        ),
        migrations.RemoveIndex(
            model_name='pt_main',
            name='patents_pt__search__a861b6_gin',
        ),
        migrations.RemoveField(
            model_name='pt_abstract',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='pt_claim',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='pt_disclosure',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='pt_interested_party',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='pt_ipc_classification',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='pt_main',
            name='search_vector',
        ),
    ]
