# Generated by Django 4.2.5 on 2023-09-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0002_alter_pt_claim_patentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_abstract',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abstract', to='patents.pt_main'),
        ),
    ]
