# Generated by Django 4.2.5 on 2023-09-14 13:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0002_remove_pt_abstract_patents_pt__search__7b4f93_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt_abstract',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pt_main',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='pt_abstract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__7b4f93_gin'),
        ),
        migrations.AddIndex(
            model_name='pt_main',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__a861b6_gin'),
        ),
    ]
