# Generated by Django 4.2.5 on 2023-09-14 14:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_pt_abstract_search_vector_pt_main_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt_claim',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pt_ipc_classification',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='pt_claim',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__612671_gin'),
        ),
        migrations.AddIndex(
            model_name='pt_ipc_classification',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__785a99_gin'),
        ),
    ]
