# Generated by Django 4.2.5 on 2023-10-03 13:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_alter_pt_abstract_patentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt_main',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='pt_main',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__a861b6_gin'),
        ),
    ]
