# Generated by Django 4.2.5 on 2023-10-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_alter_pt_main_parentappnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_interested_party',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interestedparty', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipc', to='patents.pt_main'),
        ),
    ]
