# Generated by Django 4.2.5 on 2023-10-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0004_alter_pt_interested_party_patentnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_interested_party',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interested_party', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipc_classification', to='patents.pt_main'),
        ),
    ]
