# Generated by Django 4.1.7 on 2023-03-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0004_alter_pt_interested_party_partyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_interested_party',
            name='partycountry',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='pt_interested_party',
            name='partyname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
