# Generated by Django 4.2.5 on 2023-10-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0004_pt_main_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_disclosure',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disclosure', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_interested_party',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interested_party', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipc_classification', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_priority_claim',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priority_claim', to='patents.pt_main'),
        ),
    ]
