# Generated by Django 4.2.5 on 2023-10-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0006_alter_pt_disclosure_patentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_disclosure',
            name='patentnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disclosure', to='patents.pt_main'),
        ),
    ]
