# Generated by Django 4.2.5 on 2023-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0007_alter_pt_disclosure_patentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_priority_claim',
            name='foreignappnumber',
            field=models.TextField(null=True),
        ),
    ]
