# Generated by Django 4.1.7 on 2023-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0007_alter_pt_interested_party_partyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_interested_party',
            name='partyaddressline1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pt_interested_party',
            name='partyaddressline2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pt_interested_party',
            name='partyaddressline3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pt_interested_party',
            name='partyaddressline4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pt_interested_party',
            name='partyaddressline5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
