# Generated by Django 4.1.7 on 2023-03-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0008_alter_pt_interested_party_partyaddressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipcclass',
            field=models.TextField(null=True),
        ),
    ]
