# Generated by Django 4.1.7 on 2023-04-04 20:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0009_alter_pt_ipc_classification_ipcclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt_main',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='pt_main',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__a861b6_gin'),
        ),
    ]
