# Generated by Django 4.1.7 on 2023-04-05 20:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0010_pt_main_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt_abstract',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pt_claim',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pt_disclosure',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pt_interested_party',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pt_ipc_classification',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pt_priority_claim',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='pt_abstract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__7b4f93_gin'),
        ),
        migrations.AddIndex(
            model_name='pt_claim',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__612671_gin'),
        ),
        migrations.AddIndex(
            model_name='pt_disclosure',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__bb6434_gin'),
        ),
        migrations.AddIndex(
            model_name='pt_interested_party',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__30ee24_gin'),
        ),
        migrations.AddIndex(
            model_name='pt_ipc_classification',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__785a99_gin'),
        ),
        migrations.AddIndex(
            model_name='pt_priority_claim',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_pt__search__b58528_gin'),
        ),
    ]
